# Generated by Django 3.1.2 on 2020-12-29 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2020, 12, 29), verbose_name='Премьера в мире'),
        ),
    ]
